version: '3.8'

services:

  mssql:
    hostname: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - 1434:1433
    volumes:
      - data:/var/opt/mssql
      - ./sqlserver/schema:/opt/initdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
      - MSSQL_DATABASE=guacamole

  guacd:
    hostname: guacd
    image: guacamole/guacd
    restart: always

  guacamole:
    image: guacamole/guacamole
    restart: always
    ports:
      - 8080:8080
    environment:
      - GUACD_HOSTNAME=guacd
      - SQLSERVER_HOSTNAME=mssql
      - SQLSERVER_DATABASE=guacamole
      - SQLSERVER_USER=sa
      - SQLSERVER_PASSWORD=${MSSQL_PASSWORD}
    depends_on:
      mssql:
        condition: service_started
      guacd:
        condition: service_started

volumes:
  data: